import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/Context/AppContext";
import Navbar from "@/Components/Header&Footer/Navbar";
import Footer from "@/Components/Header&Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      cz-shortcut-listen="true"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <div>
        <AppProvider>

            <Navbar />
            {children}
            <Footer />
        </AppProvider>
          
        </div>
      </body>
    </html>
  );
}
